/**
 * A conversation that hits every `UiLogItem` kind and every card state, so a CSS
 * change can be judged against all of them at once. Ordering is not arbitrary:
 * the `write_plan` / `todo_write` / assistant tail is what `planCardMarks.ts`
 * folds into the plan block.
 */
import type { ContextRef, UiLogItem } from "../../../src/protocol.js";

const REFS: ContextRef[] = [
  {
    id: "file:src/settings/theme.ts",
    kind: "file",
    label: "theme.ts",
    detail: "src/settings/theme.ts",
    target: "src/settings/theme.ts",
    status: "resolved",
    tokens: 1_240,
  },
  {
    id: "selection:src/panel.tsx:40-58",
    kind: "selection",
    label: "panel.tsx:40-58",
    detail: "src/panel.tsx, lines 40-58",
    target: "src/panel.tsx:40",
    status: "resolved",
    range: { start: 40, end: 58 },
    tokens: 310,
  },
  {
    id: "diagnostics:src/panel.tsx",
    kind: "diagnostics",
    label: "3 problems",
    detail: "3 problems in src/panel.tsx",
    target: "src/panel.tsx",
    status: "resolved",
  },
  {
    id: "url:https://ninjacode.dev/docs/theming",
    kind: "url",
    label: "ninjacode.dev/docs/theming",
    target: "https://ninjacode.dev/docs/theming",
    status: "error",
    error: "HTTP 504 fetching the page",
  },
];

const ASSISTANT_MARKDOWN = [
  "## Ce que j'ai trouvé",
  "",
  "Le thème est lu une seule fois au montage dans `usePanelTheme`, donc un changement",
  "de `workbench.colorTheme` n'atteint jamais le panneau. Trois pistes :",
  "",
  "1. Écouter `onDidChangeActiveColorTheme` côté host et republier les tokens.",
  "2. Recalculer les tokens à chaque render (coûteux, ~4 ms par frame).",
  "3. Passer par une variable CSS et laisser le navigateur invalider (**retenu**).",
  "",
  "> Le point 3 supprime l'aller-retour host → webview : la cascade fait le travail.",
  "",
  "| Piste | Coût | Fidélité thème |",
  "| --- | --- | --- |",
  "| Événement host | moyen | exacte |",
  "| Recalcul render | élevé | exacte |",
  "| Variable CSS | faible | exacte |",
  "",
  "```ts",
  "export function panelTokens(): PanelTokens {",
  "  // `readToken` lit la variable calculée, donc suit le thème actif.",
  "  return { bg: readToken(\"--bg\"), fg: readToken(\"--fg\") };",
  "}",
  "```",
  "",
  "Flux visé :",
  "",
  "```mermaid",
  "flowchart LR",
  "  theme[\"VS Code theme\"] --> vars[\"--vscode-* vars\"]",
  "  vars --> tokens[\"tokens.css\"]",
  "  tokens --> panel[\"Settings panel\"]",
  "```",
  "",
  "Détails dans la [doc de theming](https://ninjacode.dev/docs/theming).",
].join("\n");

const TODO_OUTPUT = [
  "[completed] t1: Lire usePanelTheme et repérer la lecture unique",
  "[in_progress] t2: Remplacer les tokens JS par des variables CSS",
  "[pending] t3: Couvrir le changement de thème par un test",
  "[cancelled] t4: Ajouter un événement host onDidChangeActiveColorTheme",
].join("\n");

const PLAN_SUMMARY = [
  "Le plan est écrit. Il tient en trois étapes et ne touche qu'au webview :",
  "les tokens passent en CSS, `usePanelTheme` disparaît, un test couvre le",
  "changement de thème.",
].join("\n");

export const KITCHEN_SINK_LOG: UiLogItem[] = [
  {
    kind: "user",
    text: "Le panneau de paramètres garde le thème clair après un changement de thème VS Code. Regarde @src/settings/theme.ts, @src/panel.tsx:40 et @src/panel.tsx (problems), et https://ninjacode.dev/docs/theming.",
    refs: REFS,
  },
  {
    kind: "routing",
    model: "claude-sonnet-4-6",
    label: "Claude Sonnet 4.6",
    reason: "tâche de debug UI sur un petit périmètre",
    tier: "pro",
    estimatedCredits: 12,
  },
  {
    kind: "reasoning",
    text: "Le panneau lit les couleurs une seule fois au montage.\nDonc un changement de thème n'invalide rien.\nJe vérifie d'abord usePanelTheme, puis les tokens CSS.",
  },
  {
    kind: "tool",
    id: "t-read",
    name: "read_file",
    label: "Read theme.ts",
    target: "src/settings/theme.ts",
    status: "done",
    durationMs: 42,
    lineRange: "L1-120",
    output: "export function usePanelTheme() {\n  const [tokens] = useState(readTokens);\n  return tokens;\n}",
  },
  {
    kind: "tool",
    id: "t-grep",
    name: "grep",
    label: "Grep readTokens",
    target: "src/**/*.ts",
    status: "done",
    durationMs: 118,
    argsPreview: '{"pattern":"readTokens","glob":"src/**/*.ts"}',
    output: "src/settings/theme.ts:12\nsrc/panel.tsx:47\nsrc/preview/tokens.ts:8",
  },
  { kind: "assistant", text: ASSISTANT_MARKDOWN },
  {
    kind: "tool",
    id: "t-todo",
    name: "todo_write",
    label: "Update todos",
    status: "done",
    durationMs: 4,
    output: TODO_OUTPUT,
  },
  {
    kind: "approval",
    requestId: "a-pending",
    toolName: "run_shell",
    target: "pnpm --filter ninjacode test",
    reason: "Lancer la suite de tests du webview",
    grantScope: "pnpm test",
    canRemember: true,
  },
  {
    kind: "approval",
    requestId: "a-approved",
    toolName: "read_file",
    target: "src/panel.tsx",
    reason: "Lire le composant du panneau",
    canRemember: true,
    resolved: true,
    approved: true,
    remember: true,
  },
  {
    kind: "approval",
    requestId: "a-denied",
    toolName: "run_shell",
    target: "rm -rf dist",
    reason: "Nettoyer le dossier de build avant reconstruction",
    canRemember: false,
    danger: true,
    resolved: true,
    approved: false,
  },
  {
    kind: "question",
    requestId: "q-pending",
    questions: [
      {
        id: "strategy",
        prompt: "Quelle stratégie de thème veux-tu ?",
        options: [
          { id: "css", label: "Variables CSS (recommandé)" },
          { id: "event", label: "Événement host" },
          { id: "render", label: "Recalcul à chaque render" },
        ],
      },
      {
        id: "surfaces",
        prompt: "Quelles surfaces couvrir ?",
        options: [
          { id: "panel", label: "Panneau de paramètres" },
          { id: "chat", label: "Chat" },
          { id: "plan", label: "Éditeur de plan" },
        ],
        allowMultiple: true,
      },
    ],
  },
  {
    kind: "question",
    requestId: "q-resolved",
    questions: [
      {
        id: "scope",
        prompt: "J'inclus le mode contraste élevé ?",
        options: [
          { id: "yes", label: "Oui" },
          { id: "no", label: "Non, plus tard" },
        ],
      },
    ],
    resolved: true,
    answers: [{ questionId: "scope", selectedLabels: ["Non, plus tard"] }],
  },
  {
    kind: "user_action",
    requestId: "ua-pending",
    action: "Recharge la fenêtre VS Code pour que le nouveau thème soit chargé",
    reason: "Les variables de thème sont injectées au démarrage du webview",
  },
  {
    kind: "user_action",
    requestId: "ua-resolved",
    action: "Connecte-toi au gateway",
    resolved: true,
    comment: "fait, compte pro actif",
  },
  {
    kind: "tool",
    id: "t-shell-error",
    name: "run_shell",
    label: "Run pnpm typecheck",
    target: "pnpm --filter ninjacode typecheck",
    status: "error",
    durationMs: 8_140,
    error: "src/panel.tsx(47,18): error TS2339: Property 'tokens' does not exist on type 'PanelProps'.",
  },
  {
    kind: "tool",
    id: "t-write-running",
    name: "write_file",
    label: "Write theme.css",
    target: "src/settings/theme.css",
    status: "running",
    argsPreview: '{"path":"src/settings/theme.css"}',
  },
  { kind: "status", text: "Applying edits…" },
  { kind: "error", text: "Le patch a été refusé : le fichier a changé sur le disque depuis la lecture." },
  {
    kind: "gateway_error",
    code: "insufficient_credits",
    renewsAt: "2026-09-01T00:00:00.000Z",
    planTier: "pro",
    partial: true,
  },
  {
    kind: "gateway_error",
    code: "rate_limited",
    model: "claude-sonnet-4-6",
    planTier: "pro",
  },
  { kind: "user", text: "Ok, écris-moi le plan avant de toucher au code." },
  {
    kind: "tool",
    id: "t-write-plan",
    name: "write_plan",
    label: "Write plan",
    target: "Thème du panneau de paramètres",
    status: "done",
    durationMs: 61,
  },
  {
    kind: "tool",
    id: "t-todo-plan",
    name: "todo_write",
    label: "Update todos",
    status: "done",
    durationMs: 3,
    output: TODO_OUTPUT,
  },
  { kind: "assistant", text: PLAN_SUMMARY },
];
